### ISSUE TITLE
Start creating demo site for easy access - if it's too time-consuming, then feel free to drop this and let me know!

### ISSUE THREAD

**Issue by isabelzwang** [unicef/iogt-pwa#57]

**Comment by jtoaha** [comment]
[https://unicef-iogt-pwa.web.app/](https://unicef-iogt-pwa.web.app/
)
Launched here. But it's the specific branch ('multilevel-navbar') that I was working on doesn't have Riya or Sett's changes at the moment. As of now, didn't use the 'develop' branch because our changes were not merged yet but can easily update.

Steps I took: 
1) Basically created a project on firebase (https://console.firebase.google.com/) and with the firebase command line tools linked code to the unicef-iogt-pwa firebase project
2) Ran 'npm run build'
3) And then went into the created 'build' folder and after taking care of the steps with 'firebase init' (chose 'build' as the public directory) and 'firebase deploy', site was deployed.

Can easily update which build to deploy by repeating steps above inside the branch we'd like to deploy.

How it will look in command line:
` $ What do you want to use as your public directory?`  **build**
`$  Configure as a single-page app (rewrite all urls to /index.html)?`  **Yes**
`$  File build/index.html already exists. Overwrite?` **No**
✔  Firebase initialization complete! 
After that's done: **firebase deploy**
`

**Comment by isabelzwang** [comment]
Please update this incredible site with all of the other development updates this week!
